// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJcgo1vipM0cwBerD8YBXCjtaeQZgCxoE',
    appId: '1:405105868994:web:050490592898018c04fb5b',
    messagingSenderId: '405105868994',
    projectId: 'aenrtc',
    authDomain: 'aenrtc.firebaseapp.com',
    storageBucket: 'aenrtc.appspot.com',
    measurementId: 'G-32GPCJGBFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIciWYtpypxVlEM0KTFJV91w8bI2BZTwI',
    appId: '1:405105868994:android:e03a90f8c7cc507c04fb5b',
    messagingSenderId: '405105868994',
    projectId: 'aenrtc',
    storageBucket: 'aenrtc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYvZ1RbXhd7mFgBnwGwMNNIXll7Rvzihs',
    appId: '1:405105868994:ios:e7148de6247bb24d04fb5b',
    messagingSenderId: '405105868994',
    projectId: 'aenrtc',
    storageBucket: 'aenrtc.appspot.com',
    iosBundleId: 'com.example.videocallRtc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYvZ1RbXhd7mFgBnwGwMNNIXll7Rvzihs',
    appId: '1:405105868994:ios:3acc981d75fba5f904fb5b',
    messagingSenderId: '405105868994',
    projectId: 'aenrtc',
    storageBucket: 'aenrtc.appspot.com',
    iosBundleId: 'com.example.videocallRtc.RunnerTests',
  );
}
